image: ${CI_REGISTRY}/dgs1sdt/docker-images/node:15-alpine3.10

cache:
  paths:
    - node_modules/
    - public/
    - .cache/

pages:
  stage: deploy
  script:
    - yarn install
    - yarn build:gitlab
  artifacts:
    paths:
      - public/

  only:
    - main